title: Malcolm Newson  # your name (or website title) here
logo: "/images/profilepic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  BSC Physics, minor Software Development, Co-op Physics
  <br><br>
  My professional background lies in data science, from collection to analysis. I am particularly interested in and experienced with physics-leveraged research projects, either as the primary focus or as a necessary tool.
  <br><br>
  <a href="https://www.linkedin.com/in/malcolmnewson/"target="_blank">View My LinkedIn Profile</a>
  <br><br>
  <a href="/pdfs/Resume - 2020.pdf"target="_blank">View My Resume</a> 
  <br><br>
  <a href="mailto:malcolm.newson@gmail.com"</a> 
  malcolm.newson@gmail.com
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
